# fly.toml app configuration file generated for trois-etoiles on 2024-07-02T17:34:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trois-etoiles'
primary_region = 'cdg'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
