# Generated by Django 4.2.13 on 2024-06-17 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_remove_homepageform_page_ptr_homepage_contact_form_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="contact_form",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="thank_you_text",
        ),
    ]
