# Generated by Django 4.2.13 on 2024-06-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_remove_homepage_contact_form_remove_homepage_intro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="display_title",
            field=models.BooleanField(default=True),
        ),
    ]
