# Generated by Django 4.2.13 on 2024-06-29 14:39

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "home",
            "0012_rename_conctact_us_section_text_homepage_contact_us_section_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="our_company_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="our_company_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
