# Generated by Django 4.2.13 on 2024-08-08 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_legalmansion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legalmansion",
            old_name="text",
            new_name="text_mention_legal",
        ),
        migrations.RenameField(
            model_name="legalmansion",
            old_name="Title",
            new_name="title_mention_legal",
        ),
    ]
